name: app_bar_auto_hide
description: "A new Flutter allowing automatic hiding and showing of the AppBar based on scroll events"
version: 0.0.1
homepage: "https://github.com/SwanFlutter/app_bar_auto_hide.git"

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:


